DROP TABLE CALENDAR CASCADE CONSTRAINTS;

CREATE TABLE CALENDAR (
    CALNO NUMBER    NOT NULL PRIMARY KEY,
    TITLE VARCHAR2(200)    NOT NULL,
    MEMO CLOB NULL,
    CALSTART VARCHAR2(10) NOT NULL,
    CALEND VARCHAR2(10) NULL
);

--COMMENT ON TABLE CALENDAR is 캘린더일정';
COMMENT ON COLUMN CALENDAR.CALNO is '일정 번호';
COMMENT ON COLUMN CALENDAR.TITLE is '일정 제목';
COMMENT ON COLUMN CALENDAR.MEMO is '상세 내용';
COMMENT ON COLUMN CALENDAR.CALSTART is '시작일';
COMMENT ON COLUMN CALENDAR.CALEND is '종료일';

DROP SEQUENCE CALENDAR_SEQ;

CREATE SEQUENCE CALENDAR_SEQ
    START WITH 1
    INCREMENT BY 1;
    
commit;

-- 날짜 형식을 'YYYY-MM-DD'로 변경하여 데이터 삽입
INSERT INTO CALENDAR (calno, title, memo, calstart, calend)
VALUES (CALENDAR_SEQ.NEXTVAL, '일정 등록 테스트', '일정 등록 테스트', TO_CHAR(TO_DATE('2023-12-28', 'YYYY-MM-DD'), 'YYYY-MM-DD'), TO_CHAR(TO_DATE('2023-12-28', 'YYYY-MM-DD'), 'YYYY-MM-DD'));

-- 데이터 조회
SELECT * FROM CALENDAR;

